name:                mini-aes
version:             1.0.0
github:              "czwinzscher/mini-aes"
license:             BSD3
author:              "Clemens Zwinzscher"
copyright:           "Copyright (c) 2020 Clemens Zwinzscher"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/czwinzscher/mini-aes#readme>

dependencies:
- base

ghc-options:
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Widentities
  - -Wredundant-constraints
  - -Wpartial-fields
  - -Wcompat
  - -Wunused-packages

library:
  source-dirs: src
  dependencies:
    - containers

executables:
  mini-aes:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mini-aes
    - text

tests:
  mini-aes-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mini-aes
    - tasty
    - tasty-hunit
    - tasty-smallcheck
    - smallcheck
