name:                mini-aes
version:             0.1.0.0
github:              "czwinzscher/mini-aes"
license:             BSD3
author:              "Clemens Zwinzscher"
maintainer:          "example@example.com"
copyright:           "Copyright (c) 2020 Clemens Zwinzscher"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:         Please see the README on GitHub at <https://github.com/czwinzscher/mini-aes#readme>

dependencies:
- base >= 4.7 && < 5
- containers

ghc-options:
  - -Wall
  - -O2

library:
  source-dirs: src

executables:
  mini-aes:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mini-aes
    - text

tests:
  mini-aes-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mini-aes
    - tasty
    - tasty-hunit
    - tasty-smallcheck
    - smallcheck
